### ISSUE TITLE
latency regulariser with custom hardware.

### ISSUE THREAD

**Issue by luciferamji** [ferova/MorphNetTutorials#1]
Can you use latency regulariser with custom peak compute and memory bandwidth?

Thanx in advance.

**Comment by ferova** [comment]
I added a new tutorial with a latency regularizer using custom software, however I haven't had much time to tweak much with the parameters. Please let me know if this is what you were looking for so I can close the issue.

**Comment by luciferamji** [comment]
thank you for your help.

There is a problem some of my layers are pruned to 0 .

`{'conv1_conv_1/Conv2D': 52,
 'conv2_block1_0_conv_1/Conv2D': 256,
 'conv2_block1_1_conv_1/Conv2D': 53,
 'conv2_block1_2_conv_1/Conv2D': 50,
 'conv2_block1_3_conv_1/Conv2D': 256,
 'conv2_block2_1_conv_1/Conv2D': 60,
 'conv2_block2_2_conv_1/Conv2D': 64,
 'conv2_block2_3_conv_1/Conv2D': 256,
 'conv2_block3_1_conv_1/Conv2D': 63,
 'conv2_block3_2_conv_1/Conv2D': 64,
 'conv2_block3_3_conv_1/Conv2D': 256,
 'conv3_block1_0_conv_1/Conv2D': 512,
 'conv3_block1_1_conv_1/Conv2D': 127,
 'conv3_block1_2_conv_1/Conv2D': 127,
 'conv3_block1_3_conv_1/Conv2D': 512,
 'conv3_block2_1_conv_1/Conv2D': 127,
 'conv3_block2_2_conv_1/Conv2D': 128,
 'conv3_block2_3_conv_1/Conv2D': 512,
 'conv3_block3_1_conv_1/Conv2D': 98,
 'conv3_block3_2_conv_1/Conv2D': 122,
 'conv3_block3_3_conv_1/Conv2D': 512,
 'conv3_block4_1_conv_1/Conv2D': 128,
 'conv3_block4_2_conv_1/Conv2D': 128,
 'conv3_block4_3_conv_1/Conv2D': 512,
 'conv4_block1_0_conv_1/Conv2D': 1016,
 'conv4_block1_1_conv_1/Conv2D': 212,
 'conv4_block1_2_conv_1/Conv2D': 201,
 'conv4_block1_3_conv_1/Conv2D': 1016,
 'conv4_block2_1_conv_1/Conv2D': 85,
 'conv4_block2_2_conv_1/Conv2D': 156,
 'conv4_block2_3_conv_1/Conv2D': 1016,
 'conv4_block3_1_conv_1/Conv2D': 203,
 'conv4_block3_2_conv_1/Conv2D': 182,
 'conv4_block3_3_conv_1/Conv2D': 1016,
 'conv4_block4_1_conv_1/Conv2D': 190,
 'conv4_block4_2_conv_1/Conv2D': 129,
 'conv4_block4_3_conv_1/Conv2D': 1016,
 'conv4_block5_1_conv_1/Conv2D': 254,
 'conv4_block5_2_conv_1/Conv2D': 67,
 'conv4_block5_3_conv_1/Conv2D': 1016,
 'conv4_block6_1_conv_1/Conv2D': 250,
 'conv4_block6_2_conv_1/Conv2D': 37,
 'conv4_block6_3_conv_1/Conv2D': 1016,
 'conv5_block1_0_conv_1/Conv2D': 538,
 'conv5_block1_1_conv_1/Conv2D': 512,
 'conv5_block1_2_conv_1/Conv2D': 0,
 'conv5_block1_3_conv_1/Conv2D': 538,
 'conv5_block2_1_conv_1/Conv2D': 225,
 'conv5_block2_2_conv_1/Conv2D': 0,
 'conv5_block2_3_conv_1/Conv2D': 538,
 'conv5_block3_1_conv_1/Conv2D': 330,
 'conv5_block3_2_conv_1/Conv2D': 0,
 'conv5_block3_3_conv_1/Conv2D': 538}`


i used same code as yours as well as i reduced regularisation strength to 1 e-7.

Once again  thanx for the help.you are a saviour.

**Comment by ferova** [comment]
Hey there, I don't see how this is a problem. As far as I can tell this is the normal behaviour of MorphNet. I think you should interpret this as not needing that layer as a whole. Please do check out the official presentation made by the authors [here](https://www.youtube.com/watch?v=UvTXhTvJ_wM), specially where they show complete layers being removed from models or entire residual connections being removed from ResNets.
